---
name: 27vo examen de certificación de MetaProgramadores
locale: es
type: learning
beta: false
teacher_info: ''
language: java
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
private: false
